### ISSUE TITLE
Doesn't work with terminator 1.90

### ISSUE THREAD

**Issue by danboid** [kmoppel/dumptofile#1]
I have been unable to get terminator 1.90 to register dumptofile under preferences -> plugins.

I first tried copying dump_to_file.py into both ~/.config/terminator/plugins/ and /usr/lib/python2.7/site-packages/terminatorlib/plugins/ , which is where Arch stores the default plugins but the Terminator plug-in tab doesn't list Terminal Exporter.

When I start terminator from within itself, no errors are printed but what I have noticed is that all the plugins within /usr/lib/python2.7/site-packages/terminatorlib/plugins/ consist of both a .py file and a .pyc file. So, I compiled dump_to_file.py and then renamed its compiled file to dump_to_file.py.pyc and copied it into both of the terminator plugin path dirs but still Terminator doesn't show it under its plugins tab.

**Comment by danboid** [comment]
Also, I had to put parentheses around the `e` on the last line of the script to get it to compile with python 3.6.0.

**Comment by kmoppel** [comment]
Thanks for the report! Indeed, same problem for me also with 1.90 (Ubuntu 16.04 ). I'm still using the repo version (0.98) so didn't have that problem. Will try to look into soonish...if you manage to find out the cause in the mean time please let me know. Thanks!

**Comment by kmoppel** [comment]
@danboid version from this [branch](https://github.com/kmoppel/dumptofile/tree/terminator-1.90) should work now :)
